### ISSUE TITLE
Modifying url with paginate

### ISSUE THREAD

**Issue by prettymuchbryce** [rchipka/node-osmosis#160]
Hello. Great project you have here.

I noticed `paginate` helpfully allows you to modify the query params of the request, however there doesn't seem to be a way to use it to manipulate the url itself. I am scraping something wherein the URI itself changes. E.g. `foo.com/bar/5/`, `foo.com/bar/6/`, etc.

I can wrap my osmosis call as a whole in a loop, but then I am not exactly taking advantage of any parallelism. Do you have any suggestions of how I should handle a case like this? Should we add this ability into `paginate`, or is there something existing I am missing?

**Comment by jaspersorrio** [comment]
I am facing the same issue... ):

**Comment by NegativeIQ** [comment]
There is a way for that, i guess its just doesnt have example usage in readme/docs, but you can always check tests.
Anyway here is piece of code from one of my scrappers for forum running VB 3.x i think.
```
osmosis
.get(urllink + '&order=desc&page=', { page: 1 })
.paginate({ page: +1 }, 50)
```
page: 1 means starting from 1, page: +1 means step is 1, and 50 is max pages to scrap (im not sure what happens if there is less pages then max)

So for your example it would be something like:
```
osmosis
.get('foo.com/bar/', { page: 1 })
.paginate({ page: +1 }, 50)
```

And if page argument/parameter is not the last one i have no idea how to paginate without custom solution.

**Comment by redgenie** [comment]
How to handle pagination that is done with alphabet rather than numbers? As in pagination by letters.

**Comment by ysolomont** [comment]
This solution doesn't work. It returns:

foo.com/bar/?page=1
foo.com/bar/?page=2 etc.

The question remains, how do you iterate through URLs? foo.com/bar/5/, foo.com/bar/6/, etc.

**Comment by NegativeIQ** [comment]
If there is a next page link, you could pass that selector to paginate... But i think your best bet would be generating your own urls (that are already including page number) and pass them to get() method.

But i do agree current pagination requires overhaul.

**Comment by rchipka** [comment]
In 0.1.5 `.paginate` supports `function (context, data)` as its first argument.

You can use the the URL object by accessing `document.request`.

It can either return a string URL or object for query params.

Asyncifying these function args will come in a future major version.
