### ISSUE TITLE
Should work with german umlauts

### ISSUE THREAD

**Issue by jmartsch** [rchipka/node-osmosis#25]
In my resulting console output all umlauts like öäüß are destroyed.
The site is encoded with charset=iso-8859-1

**Comment by rc0x03** [comment]
Would you be able to provide a link to the site?

**Comment by jmartsch** [comment]
http://www.gelbeseiten.de/hotel/muenster
first and sixth entry contain umlauts



------ Originalnachricht ------
Von: "rc0x03" <notifications@github.com>
An: "rc0x03/node-osmosis" <node-osmosis@noreply.github.com>
Cc: "Jens Martsch" <jmartsch@gmail.com>
Gesendet: 18.06.2015 03:29:34
Betreff: Re: [node-osmosis] Should work with german umlauts (#25)

**Comment by andineck** [comment]
I just ran into the same problem. 
Here's an example:

```js
var url = 'http://www.tutti.ch/ganze-schweiz?q=Espresso';
/*
 Response Headers:
   Content-Encoding:gzip
   oContent-Type:text/html; charset=ISO-8859-1
 */


// needle example
var needle = require('needle');
needle.get(url, function(error, response) {
  if (!error && response.statusCode == 200) {

    console.log('umlaute needle', countUmlaute(response.body));
    //console.log(response.body);

  }
});

// osmosis example
var osmosis = require('osmosis');
osmosis
  .get(url)
  .find('body')
  .set('body')
  .then(function(context, data, next) {
    console.log('umlaute osmosis', countUmlaute(data.body));
    //console.log(data.body);
  });


function countUmlaute(str) {
  var ae = str.split('ä').length - 1;
  var oe = str.split('ö').length - 1;
  var ue = str.split('ü').length - 1;
  return {'ä': ae, 'ö': oe, 'ü': ue}
}

/*
 -> print out:
 umlaute osmosis { 'ä': 0, 'ö': 0, 'ü': 0 }
 umlaute needle { 'ä': 36, 'ö': 24, 'ü': 67 }
 */

```

Any ideas how to fix this?

**Comment by andineck** [comment]
I also tried with the option
```js
      .config({decode: false})
```
but it makes things worse...

**Comment by rc0x03** [comment]
I have yet to look into this but the issue may be because it's an encoding that `libxmljs` doesn't support. If that's the case, there's nothing Osmosis can do to change that. All encoding functionality is handled by `libxmljs` and Osmosis won't ever include supplemental encoding support. However, Osmosis can have a global text pre-processor callback that will be given any requested data and return that data in UTF-8. That way a user can create their own text encoding converter function using a library of their choice.
