### ISSUE TITLE
.done() should not return empty callback

### ISSUE THREAD

**Issue by riyadhalnur** [rchipka/node-osmosis#86]
It would make more sense for `.done()` to return a array of the data in the callback to complement `.data()` which fires on each data item.

**Comment by rchipka** [comment]
The reason `.done()` isn't given an array by default is because Osmosis would have to keep all the data values in memory. Very often Osmosis is used to scrape a large amount of data objects, which would consume many resources.

If you'd like to receive the data as an array you can use nested `.set()` calls.

```javascript
osmosis.get('example.com')
.set({
    results: [
        osmosis.find('ul.results > li')
        .set({
            title: 'h1',
            images: [ 'img@src' ]
        })
    ]
})
.data(function(data) {
    /*
    {
        results: [
            { title: ..., images [ ... ] },
            ...,
            ...
        ]
    }
    */
})
```

The upcoming version (1.0.0) comes with the ability to set an array as the root data object, which means you can skip the { results: } part, like this:

```javascript
osmosis.get('example.com')
.set([
    osmosis.find('ul.results > li')
    .set({
        title: 'h1',
        images: [ 'img@src' ]
    })
])
.data(function(data) {
    /*
    {
        results: [
            { title: ..., images [ ... ] },
            ...,
            ...
        ]
    }
    */
})
```

**Comment by riyadhalnur** [comment]
Yeah the memory part is a blocker and I completely agree on that. My thought process is that, each data set would be cached in memcache-like data stores. The performance hit wouldn't be that noticeable.

With nested sets though, taking the first example, would the resulting `data` parameters include all the list items under the `ul.results`?

**Comment by rchipka** [comment]
Yes, `data.results` would be an array. To access the first image of the first result you would write `data.results[0].images[0]`.
